name: deploy:docs

on:
  push:
    branches:
      - master
      - ci/deploy-docs

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy docs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DOCS_DEPLOY_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DOCS_DEPLOY_AWS_SECRET_ACCESS_KEY }}
        run: |
          cd docs/
          npm run publish
